version: '3'
services:
  application:
    user: node
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 16
    command: sleep infinity
    env_file: .env.development
    ports:
      - 3000:3000
    volumes:
      - ..:/iteacher-api-gateway
